config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "home#index"

  get :dashboard, to: "dashboard#index"
  
  resources :tweets, only: :create

  resources :usernames, only: [:new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: { sensitive_case: false }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :redirect_to_username_form, if: -> { user_signed_in? && current_user.username.blank? }

    protected

    def after_sign_in_path_for(resources)
        dashboard_path
    end

    def redirect_to_username_form
        redirect_to new_username_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @tweets = Tweet.paginate(:page => params[:page], per_page: 20).order('created_at DESC')
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @tweets = Tweet.paginate(:page => params[:page], per_page: 5).order('created_at DESC')
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        tweet = Tweet.new(tweet_params.merge(user: current_user))

        if tweet.save
            redirect_to(dashboard_path)
        end
    end

    private

    def tweet_params
        params.require(:tweet).permit(:body)
    end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :redirect_to_username_form

    def new
    end

    def update
      if username_params[:username].present? && current_user.update(username_params)
        flash[:notice] = "Username successfully updated"
        redirect_to dashboard_path
      else
        flash[:alert] = username_params[:username].blank? ? "Please set a username" : current_user.full_messages.join(', ') 
        redirect_to new_username_path
      end
    end

    private

    def username_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.erb
<div class="container text-start mt-5">
  <div class="row">
    <div class="col gap-3">
      <div class="perfil d-flex align-items-center justify-content-between">
        <span>@<%= current_user.username %></span>
        <%= link_to 'Update Username', new_username_path, class: "btn btn-primary" %>
      </div>
      <%= form_with model: Tweet.new, url: tweets_path, class: "mt-3", method: :post, local: true do |f| %>
        <%= f.text_field :body, class: "form-control form-control-lg fs-6 mb-3", placeholder: "Type something!!" %>
        <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
      </div>
    <div class="col">
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
        <li class="list-group-item d-flex align-items-center justify-content-between">
          <span>@<%= tweet.user.username %> | <%= tweet.body %></span> 
          <span style="font-size: 12px; color: #3065ac; font-weight: bold;">
            <%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %> 
          </span>
        </li>
      <% end %>
      
      
      <div class="apple_pagination">
        <!-- <div class="page_info">
          <%= page_entries_info @tweets %>
        </div> -->
        <%= will_paginate @tweets, :container => false %>
      </div>
      </ul>
    </div>
    <div class="col">
      <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container text-start mt-5">
  <div class="row">
    <div class="col gap-3">
      <h1>Welcome to The Mini Twi!</h1>
      <h3 class="fs-4">Make posts and see other posts!!</h3>
    </div>
    <div class="col">
      <ul class="list-group">

        <% @tweets.each do |tweet| %>
          <li class="list-group-item d-flex align-items-center justify-content-between">
            <span>@<%= tweet.user.username %> | <%= tweet.body %></span> 
            <span style="font-size: 12px; color: #3065ac; font-weight: bold;">
              <%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %> 
            </span>
          </li>
        <% end %>
        
        
        <div class="apple_pagination">
          <!-- <div class="page_info">
            <%= page_entries_info @tweets %>
          </div> -->
          <%= will_paginate @tweets, :container => false %>
        </div>
      </ul>
    </div>
    <div class="col">
      <%= link_to "Sign Up" , new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "Sign In" , new_user_session_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mini Twi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
    <div class="container-sm" style="max-width: 500px;">
      <%= render "shared/flashes" %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/usernames/new.html.erb
<div class="container-sm mt-5" style="max-width: 500px;">

    <h2>Set your username</h2>

    <%= form_with model: current_user, local: true, url: username_path(current_user) do |f| %>
			<div class="mb-2 mt-3">
				<%= f.label :username, class: "form-label" %>
				<%= f.text_field :username, class: "form-control" %>
			</div>

			<%= f.submit "Set username", class: "btn btn-primary" %>
    <% end %>
</div>